sudo: false
language: node_js
node_js:
  - lts/*
cache: npm
branches:
  only:
    - dev
before_script:
  - npm install -g @vue/cli
  - npm install -g @vue/cli-service-global
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  target_branch: master
  keep-history: false
  on:
    branch: dev
  local-dir: dist